import { useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { ArrowUpRight, Building2, CalendarDays, CheckCircle2, CircleHelp, FileText, KeyRound, Plus, Search, Pencil, Trash2, Wrench, Image as ImageIcon } from 'lucide-react';
import { usePortal } from '../../hooks/usePortal';
import type { Collection, Entity } from '../../lib/types';
import { formatDate, money } from '../../lib/utils';
import { Confirm, DocumentActions, Empty, Field, Gateway, Modal, PageHeader, Section, Status, Tabs } from '../../components/UI';
import { EntityEditor, type EditField } from '../../components/EntityEditor';
const gallery=[{src:'/images/fachada.jpg',title:'Nuestro edificio',alt:'Fachada del edificio en la esquina, con acceso en planta baja'},{src:'/images/hall.jpg',title:'El hall de entrada',alt:'Hall de entrada con ventanales, plantas y zona de recepción'},{src:'/images/sum.jpg',title:'Salón de usos múltiples',alt:'SUM equipado con mesas, sillas y amplios ventanales'},{src:'/images/vista.jpg',title:'La vista desde el edificio',alt:'Vista panorámica de la ciudad desde el edificio'}];
export function BuildingGallery(){const [selected,setSelected]=useState<typeof gallery[number]>();return <><div className="building-gallery">{gallery.map(g=><button className="gallery-item" key={g.src} onClick={()=>setSelected(g)}><img src={g.src} alt={g.alt} loading="lazy"/><span>{g.title}<ImageIcon size={18}/></span></button>)}</div>{selected&&<Modal title={selected.title} onClose={()=>setSelected(undefined)} wide><img className="full-photo" src={selected.src} alt={selected.alt}/></Modal>}</>;}
export function BuildingPage(){return <><PageHeader title="Mi edificio" description="La información del consorcio, en un solo lugar."/><div className="gateway-list"><Gateway to="/edificio/expensas" title="Expensas" description="Liquidación actual y meses anteriores" icon={<FileText/>}/><Gateway to="/edificio/reuniones" title="Reuniones" description="Próximo encuentro, propuestas y encuestas" icon={<CalendarDays/>}/><Gateway to="/edificio/documentos" title="Documentos" description="Actas, reglamento y archivos del edificio" icon={<FileText/>}/><Gateway to="/edificio/cuentas" title="Cuentas del edificio" description="Ingresos, gastos y presupuestos" icon={<Building2/>}/></div></>;}
export function DocumentsPage(){const {data}=usePortal();const [q,setQ]=useState('');const [cat,setCat]=useState('Todas');const docs=data.documents.filter(x=>(cat==='Todas'||x.category===cat)&&`${x.title} ${x.description}`.toLowerCase().includes(q.toLowerCase()));return <><PageHeader title="Documentos" description="La biblioteca del consorcio." back="/edificio"/><div className="toolbar"><label className="search-field"><Search size={20}/><input placeholder="Buscar un documento" aria-label="Buscar documento" value={q} onChange={e=>setQ(e.target.value)}/></label><Field label="Categoría"><select value={cat} onChange={e=>setCat(e.target.value)}>{['Todas',...new Set(data.documents.map(d=>d.category))].map(c=><option key={c}>{c}</option>)}</select></Field></div><div className="list">{docs.map(d=><div className="list-row" key={d.id}><span className="file-icon"><FileText/></span><div className="row-main"><span className="eyebrow">{d.category}</span><h3>{d.title}</h3><p>{formatDate(d.date)} · Documento demo</p></div><DocumentActions attachment={d.attachment}/></div>)}{!docs.length&&<Empty/>}</div><Link className="text-link" to="/edificio/obras">Seguimiento de obras<ArrowUpRight size={18}/></Link></>;}
export function MorePage(){return <><PageHeader title="Más" description="La vida del edificio, más allá de lo cotidiano."/><div className="gateway-list"><Gateway to="/mas/disponibilidades" title="Disponibilidades" description="Departamentos y cocheras" icon={<KeyRound/>}/><Gateway to="/mas/objetos" title="Objetos perdidos" description="Objetos encontrados en espacios comunes" icon={<Search/>}/><Gateway to="/mas/preguntas" title="Preguntas frecuentes" description="Respuestas a consultas habituales" icon={<CircleHelp/>}/><Gateway to="/mas/calendario" title="Calendario" description="Fechas y actividades del consorcio" icon={<CalendarDays/>}/><Gateway to="/mas/estado" title="Estado del edificio" description="Servicios, espacios y trabajos en curso" icon={<Building2/>}/></div></>;}
export function StatusList({compact=false}:{compact?:boolean}){const {data}=usePortal();return <div className="status-list">{data.statuses.slice(0,compact?3:undefined).map(s=>{const warning=/mantenimiento|corte|cerrado|reparación/i.test(s.status??'');return <div className="status-row" key={s.id}><span className={warning?'state-symbol warning':'state-symbol'}>{warning?<Wrench size={18}/>:<CheckCircle2 size={18}/>}</span><div className="row-main"><strong>{s.title}</strong>{!compact&&<p>{s.description}</p>}</div><span className={warning?'state-text warning':'state-text'}>{s.status}</span></div>;})}</div>;}
export function StatePage(){return <><PageHeader title="Estado del edificio" description="Información actualizada por la administración." back="/mas"/><StatusList/><Section title="Obras en curso" action={<Link className="text-link" to="/edificio/obras">Ver avances<ArrowUpRight size={18}/></Link>}><WorkSummary/></Section><Section title="Nuestros espacios"><BuildingGallery/></Section></>;}
function WorkSummary(){const {data}=usePortal();return <>{data.works.map(w=><Link key={w.id} to="/edificio/obras" className="list-row"><Wrench/><div className="row-main"><h3>{w.title}</h3><p>{w.status} · {w.progress??0}% de avance</p></div><ArrowUpRight size={20}/></Link>)}{!data.works.length&&<Empty>No hay obras en curso.</Empty>}</>;}
export function WorksPage(){const {data}=usePortal();return <><PageHeader title="Obras y avances" description="Seguimiento de los trabajos del edificio." back="/edificio/documentos"/>{data.works.map(w=><section className="work-detail" key={w.id}><Status tone="amber">{w.status}</Status><h2>{w.title}</h2><p>{w.description}</p><dl className="facts"><div><dt>Inicio</dt><dd>{formatDate(w.startDate??w.date)}</dd></div><div><dt>Presupuesto</dt><dd>{money(w.amount??0)}</dd></div><div><dt>Proveedor</dt><dd>{w.provider}</dd></div></dl><div className="progress-label"><strong>Avance de la obra</strong><span>{w.progress??0}%</span></div><progress value={w.progress??0} max={100} aria-label="Avance de la obra"/><h3>Etapas del trabajo</h3><ul className="milestones">{(w.milestones??['Trabajo registrado por administración']).map(m=><li key={m}>{m}</li>)}</ul><p className="muted">Última actualización: {formatDate(w.date)}</p>{w.summary&&<p>{w.summary}</p>}<DocumentActions attachment={w.attachment} label="Ver presupuesto"/>{w.image&&<img className="full-photo" src={w.image} alt={`Archivo de la obra ${w.title}`}/>}</section>)}{!data.works.length&&<Empty>No hay obras publicadas.</Empty>}<Section title="Vista desde el edificio"><figure className="building-view"><img src="/images/vista.jpg" alt="Vista de la ciudad desde el edificio" loading="lazy"/><figcaption>Fotografía del edificio. El seguimiento de la obra contiene datos demo.</figcaption></figure></Section></>;}
export function ListingsPage(){const {data}=usePortal();const [type,setType]=useState('Todas');return <><PageHeader title="Disponibilidades" description="Información compartida por la comunidad. Datos demo." back="/mas"/><Tabs items={['Todas','Departamento','Cochera'].map(x=>({id:x,label:x==='Todas'?x:`${x}s`}))} value={type} onChange={setType}/><div className="list">{data.listings.filter(x=>type==='Todas'||x.category===type).map(x=><div className="list-row" key={x.id}><KeyRound/><div className="row-main"><Status>{x.type}</Status><h3>{x.title}</h3><p>{x.description}</p></div><Link className="button secondary" to={`/servicios/chat?consulta=${encodeURIComponent(x.title)}`}>Consultar<ArrowUpRight size={18}/></Link></div>)}</div></>;}
export function LostPage(){const {data}=usePortal();return <><PageHeader title="Objetos perdidos" description="Quizás lo que buscás está acá." back="/mas"/><div className="list">{data.lost.map(x=><div className="lost-row" key={x.id}>{x.image?<img src={x.image} alt={`Ilustración demo: ${x.title}`} loading="lazy"/>:<span className="lost-placeholder"><Search size={32}/></span>}<div className="row-main"><Status>{x.status}</Status><h3>{x.title}</h3><p>{x.description}</p><p className="muted">{x.place} · {formatDate(x.date)}</p>{x.image&&<small className="muted">Imagen ilustrativa demo</small>}</div><Link className="button secondary" to={`/servicios/chat?consulta=${encodeURIComponent(x.title)}`}>Es mío<ArrowUpRight size={18}/></Link></div>)}</div>{!data.lost.length&&<Empty>No hay objetos en custodia.</Empty>}</>;}
export function FaqPage(){const {data}=usePortal();const [q,setQ]=useState('');const faqs=data.faqs.filter(f=>`${f.title} ${f.description} ${f.category}`.toLowerCase().includes(q.toLowerCase()));return <><PageHeader title="Preguntas frecuentes" description="Respuestas para el día a día." back="/mas"/><label className="search-field"><Search size={20}/><input aria-label="Buscar pregunta" placeholder="¿Qué necesitás saber?" value={q} onChange={e=>setQ(e.target.value)}/></label><div className="faq-list">{faqs.map(f=><details key={f.id}><summary><span><small>{f.category}</small>{f.title}</span><Plus size={20}/></summary><p>{f.description}</p></details>)}</div>{!faqs.length&&<Empty/>}<Link className="text-link" to="/servicios/chat">Hacer otra consulta<ArrowUpRight size={18}/></Link></>;}
const baseFields:EditField[]=[{key:'title',label:'Título',required:true},{key:'description',label:'Descripción',type:'textarea'}];
const configs:{key:Collection;label:string;fields:EditField[]}[]=[
 {key:'documents',label:'Documentos',fields:[...baseFields,{key:'category',label:'Categoría',options:['Actas','Reglamento','Presupuestos','Facturas','Seguros','Certificados','Convocatorias','Informes']},{key:'date',label:'Fecha',type:'date',required:true}]},
 {key:'works',label:'Obras',fields:[...baseFields,{key:'provider',label:'Proveedor',required:true},{key:'amount',label:'Presupuesto ($)',type:'number',required:true},{key:'status',label:'Estado',options:['Planificada','En ejecución','Finalizada','Pausada']},{key:'progress',label:'Avance (%)',type:'number',required:true},{key:'startDate',label:'Fecha de inicio',type:'date',required:true},{key:'summary',label:'Última actualización',type:'textarea'}]},
 {key:'listings',label:'Disponibilidades',fields:[...baseFields,{key:'category',label:'Tipo de espacio',options:['Departamento','Cochera']},{key:'type',label:'Operación',options:['Alquiler','Venta']},{key:'contact',label:'Contacto demo'}]},
 {key:'contacts',label:'Contactos',fields:[...baseFields,{key:'category',label:'Especialidad',options:['Administración','Encargado','Ascensores','Electricista','Plomero','Emergencias','Otros proveedores']},{key:'contact',label:'Referencia de contacto (demo)'},{key:'phone',label:'Teléfono (solo demo)'},{key:'email',label:'Email (solo demo)',type:'email'}]},
 {key:'faqs',label:'Preguntas frecuentes',fields:[{key:'title',label:'Pregunta',required:true},{key:'description',label:'Respuesta',type:'textarea',required:true},{key:'category',label:'Categoría',options:['SUM','Expensas','Reclamos','Administración','Reglamento','Reuniones']}]},
 {key:'lost',label:'Objetos perdidos',fields:[...baseFields,{key:'place',label:'Lugar',required:true},{key:'date',label:'Fecha',type:'date',required:true},{key:'status',label:'Estado',options:['En custodia','Devuelto']},{key:'contact',label:'Contacto demo'}]},
 {key:'statuses',label:'Estado del edificio',fields:[...baseFields,{key:'status',label:'Estado',options:['Operativo','Habilitado','En mantenimiento','Corte programado','Fuera de servicio']}]}];
export function AdminContentPage(){const {data,save,remove,notify}=usePortal();const [params,setParams]=useSearchParams();const config=configs.find(c=>c.key===params.get('tab'))??configs[0];const [editing,setEditing]=useState<Entity|null|undefined>();const [deleting,setDeleting]=useState<Entity>();const [q,setQ]=useState('');return <><PageHeader title="Contenido" description="Documentos e información de los espacios compartidos." action={<button className="button" onClick={()=>setEditing(null)}><Plus size={19}/>Agregar</button>}/><Tabs items={configs.map(c=>({id:c.key,label:c.label}))} value={config.key} onChange={x=>{setParams({tab:x});setQ('');}}/><label className="search-field"><Search size={20}/><input aria-label="Buscar contenido" placeholder={`Buscar en ${config.label.toLowerCase()}`} value={q} onChange={e=>setQ(e.target.value)}/></label><div className="list">{data[config.key].filter(x=>x.title.toLowerCase().includes(q.toLowerCase())).map(x=><div className="list-row" key={x.id}><div className="row-main"><h3>{x.title}</h3><p>{x.category??x.status} {x.description&&`· ${x.description}`}</p></div><div className="row-actions">{x.attachment&&<DocumentActions attachment={x.attachment}/>}<button className="icon-button" title={`Editar ${x.title}`} aria-label={`Editar ${x.title}`} onClick={()=>setEditing(x)}><Pencil size={19}/></button><button className="icon-button" title={`Eliminar ${x.title}`} aria-label={`Eliminar ${x.title}`} onClick={()=>setDeleting(x)}><Trash2 size={19}/></button></div></div>)}</div>{data[config.key].length===0&&<Empty>No hay contenido publicado en esta sección.</Empty>}{(editing!==undefined||params.get('new')==='1')&&<EntityEditor title={editing?'Editar contenido':`Agregar · ${config.label}`} fields={config.fields} item={editing??undefined} attachment={['documents','works','lost'].includes(config.key)} onSave={item=>{if(item.attachment?.type.startsWith('image/'))item.image=item.attachment.url;save(config.key,item);notify('Contenido guardado. Ya está disponible en Propietario.');}} onClose={()=>{setEditing(undefined);setParams({tab:config.key});}}/>}{deleting&&<Confirm description={`Se eliminará “${deleting.title}” de ambas vistas.`} onClose={()=>setDeleting(undefined)} onConfirm={()=>{remove(config.key,deleting.id);notify('Contenido eliminado.');}}/>}</>;}
