import { useEffect, useId, useRef, useState, type ReactNode } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, X, FileText, Download, Paperclip, CheckCircle2, ChevronRight } from 'lucide-react';
import type { Attachment } from '../lib/types';
import { demoPdf, downloadFile, readAttachment } from '../lib/utils';

export function PageHeader({title,description,action,back}:{title:string;description?:string;action?:ReactNode;back?:string}) {return <header className="page-heading">{back&&<Link className="back-link" to={back}><ArrowLeft size={18}/>Volver</Link>}<div className="heading-line"><div><h1>{title}</h1>{description&&<p>{description}</p>}</div>{action}</div></header>;}
export function Section({title,action,children}:{title:string;action?:ReactNode;children:ReactNode}){return <section className="section"><div className="section-heading"><h2>{title}</h2>{action}</div>{children}</section>;}
export function Status({children,tone='neutral'}:{children:ReactNode;tone?:'neutral'|'green'|'amber'|'red'}){return <span className={`status status-${tone}`}>{children}</span>;}
export function Empty({children='No hay resultados para esta búsqueda.'}:{children?:ReactNode}){return <div className="empty"><CheckCircle2 size={28}/><p>{children}</p></div>;}
export function Field({label,children,hint}:{label:string;children:ReactNode;hint?:string}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>;}
export function Tabs({items,value,onChange}:{items:{id:string;label:string}[];value:string;onChange:(id:string)=>void}){return <div className="tabs" aria-label="Secciones">{items.map(x=><button key={x.id} className={value===x.id?'active':''} aria-pressed={value===x.id} onClick={()=>onChange(x.id)}>{x.label}</button>)}</div>;}
export function Modal({title,onClose,children,wide=false}:{title:string;onClose:()=>void;children:ReactNode;wide?:boolean}){const ref=useRef<HTMLDialogElement>(null);const titleId=useId();useEffect(()=>{const previous=document.activeElement as HTMLElement;const dialog=ref.current;dialog?.showModal();const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{dialog?.close();document.body.style.overflow=old;previous?.focus();};},[]);return <dialog className={`modal ${wide?'modal-wide':''}`} ref={ref} aria-labelledby={titleId} onCancel={e=>{e.preventDefault();onClose();}} onClick={e=>{if(e.target===e.currentTarget)onClose();}}><div className="modal-inner"><div className="modal-heading"><h2 id={titleId}>{title}</h2><button className="icon-button" title="Cerrar" aria-label="Cerrar" onClick={onClose}><X/></button></div>{children}</div></dialog>;}
export function Confirm({title='Confirmar eliminación',description,onConfirm,onClose}:{title?:string;description:string;onConfirm:()=>void;onClose:()=>void}){return <Modal title={title} onClose={onClose}><p>{description}</p><div className="form-actions"><button className="button secondary" onClick={onClose}>Volver</button><button className="button danger" onClick={()=>{onConfirm();onClose();}}>Confirmar</button></div></Modal>;}
export function UploadField({value,onChange,label='Adjuntar archivo'}:{value?:Attachment;onChange:(value:Attachment|undefined)=>void;label?:string}){const [error,setError]=useState('');return <div><Field label={label} hint="PDF, JPG, PNG, WebP o TXT. Hasta 1 MB."><input type="file" accept=".pdf,.jpg,.jpeg,.png,.webp,.txt" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{onChange(await readAttachment(f));setError('');}catch(err){setError((err as Error).message);}e.target.value='';}}/></Field>{error&&<p className="error" role="alert">{error}</p>}{value&&<div className="attachment-label"><Paperclip size={18}/><span>{value.name}</span><button className="icon-button" title="Quitar archivo" aria-label="Quitar archivo" onClick={()=>onChange(undefined)} type="button"><X size={18}/></button></div>}</div>;}
export function DocumentActions({attachment=demoPdf,label='Ver PDF'}:{attachment?:Attachment;label?:string}){const [open,setOpen]=useState(false);return <><div className="document-actions"><button className="button secondary" onClick={()=>setOpen(true)}><FileText size={18}/>{label}</button><button className="icon-button" title="Descargar documento" aria-label="Descargar documento" onClick={()=>downloadFile(attachment)}><Download size={20}/></button></div>{open&&<Modal title={attachment.name} onClose={()=>setOpen(false)} wide>{attachment.type.startsWith('image/')?<img className="document-image" src={attachment.url} alt={attachment.name}/>:<iframe className="document-preview" src={attachment.url} title={attachment.name}/>}<button className="button" onClick={()=>downloadFile(attachment)}><Download size={18}/>Descargar archivo</button></Modal>}</>;}
export function Gateway({to,title,description,icon}:{to:string;title:string;description:string;icon:ReactNode}){return <Link className="gateway" to={to}><span className="gateway-icon">{icon}</span><span><strong>{title}</strong><small>{description}</small></span><ChevronRight size={21}/></Link>;}
