import { useEffect, useState } from 'react';
import { BrowserRouter, Link, NavLink, Outlet, Route, Routes, useLocation } from 'react-router-dom';
import { Building2, FileText, Home, LayoutDashboard, Menu, MessageCircle, MoreHorizontal, Newspaper, Settings2, ShieldAlert, Sparkles, Wrench, X } from 'lucide-react';
import { PortalProvider, usePortal } from './hooks/usePortal';
import { HomePage, AdminHomePage } from './features/owner/Home';
import { NoticesPage, NoticeDetail } from './features/notices/Notices';
import { AdminContentPage, BuildingPage, DocumentsPage, FaqPage, ListingsPage, LostPage, MorePage, StatePage, WorksPage } from './features/content/Content';
import { FinancesPage, ExpensesPage } from './features/finances';
import { ServicesPage, ChatPage, ContactsPage, UrgenciesPage, AdminServicesPage, SumPage, IssuesPage } from './features/services';
import { MeetingsPage, PollsPage, CalendarPage, AdminCommunityPage } from './features/community';
import './styles/global.css';

const ownerNav=[{to:'/',label:'Inicio',Icon:Home,end:true},{to:'/novedades',label:'Novedades',Icon:Newspaper},{to:'/edificio',label:'Mi edificio',Icon:Building2},{to:'/servicios',label:'Servicios',Icon:Wrench},{to:'/mas',label:'Más',Icon:MoreHorizontal}];
const adminNav=[{to:'/admin',label:'Inicio',Icon:LayoutDashboard,end:true},{to:'/admin/comunicaciones',label:'Comunicaciones',Icon:MessageCircle},{to:'/admin/finanzas',label:'Finanzas',Icon:FileText},{to:'/admin/comunidad',label:'Comunidad',Icon:Building2},{to:'/admin/servicios',label:'Servicios',Icon:Wrench},{to:'/admin/contenido',label:'Contenido',Icon:Settings2}];

function Header({admin}:{admin:boolean}){const location=useLocation();return <header className="site-header"><div className="header-inner"><Link to={admin?'/admin':'/'} className="brand"><span className="brand-mark"><Building2 size={25}/></span><span><strong>Portal del Edificio</strong><small>Información y gestión del consorcio</small></span></Link><div className="view-controls"><span className="demo-label">Modo demostración</span><div className="role-switch" aria-label="Cambiar vista"><Link className={!admin?'active':''} to={location.pathname.startsWith('/admin')?'/':location.pathname} state={{view:'owner'}}><Home size={16}/>Propietario</Link><Link className={admin?'active':''} to={location.pathname.startsWith('/admin')?location.pathname:'/admin'} state={{view:'admin'}}><LayoutDashboard size={16}/>Administración</Link></div></div></div>{!admin&&<OwnerNav/>}</header>}
function OwnerNav(){return <nav className="owner-nav" aria-label="Navegación principal"><div className="owner-nav-inner">{ownerNav.map(({to,label,Icon,end})=><NavLink key={to} to={to} end={end}><Icon size={22}/><span>{label}</span></NavLink>)}<NavLink className="nav-urgencies" to="/servicios/urgencias"><ShieldAlert size={20}/><span>Urgencias</span></NavLink></div></nav>}
function AdminSidebar(){return <aside className="admin-sidebar"><p>Administración · Demo</p>{adminNav.map(({to,label,Icon,end})=><NavLink key={to} to={to} end={end}><Icon size={20}/><span>{label}</span></NavLink>)}<button className="button secondary reset-button" onClick={()=>window.dispatchEvent(new CustomEvent('open-demo-reset'))}><Sparkles size={17}/>Restablecer datos demo</button></aside>}
function AdminMobileMenu(){const [open,setOpen]=useState(false);return <div className="admin-mobile-menu"><span>Administración · Demo</span><button className="button secondary small" aria-expanded={open} onClick={()=>setOpen(v=>!v)}>{open?<X size={18}/>:<Menu size={18}/>}Menú</button>{open&&<div className="drawer-backdrop" onClick={()=>setOpen(false)}><div className="drawer-nav" onClick={e=>e.stopPropagation()}><div className="drawer-heading"><strong>Secciones</strong><button className="icon-button" aria-label="Cerrar menú" title="Cerrar menú" onClick={()=>setOpen(false)}><X size={20}/></button></div>{adminNav.map(({to,label,Icon,end})=><NavLink key={to} to={to} end={end} onClick={()=>setOpen(false)}><Icon size={20}/>{label}</NavLink>)}<ResetDemoButton/></div></div>}</div>}
function ResetDemoButton(){const {reset}=usePortal();return <button className="button secondary" onClick={()=>{if(window.confirm('¿Restablecer todos los datos demo? Se perderán los cambios locales.'))reset();}}><Sparkles size={17}/>Restablecer datos demo</button>}
function ResetListener(){const {reset}=usePortal();return <>{useResetEvent(reset)}</>}
function useResetEvent(reset:()=>void){const [open,setOpen]=useState(false);useEffect(()=>{const handler=()=>setOpen(true);window.addEventListener('open-demo-reset',handler);return()=>window.removeEventListener('open-demo-reset',handler)},[]);return open?<div className="reset-popover"><p>¿Restablecer todos los datos demo? Se perderán los cambios locales.</p><div className="form-actions"><button className="button secondary" onClick={()=>setOpen(false)}>Cancelar</button><button className="button" onClick={()=>{reset();setOpen(false)}}>Restablecer</button></div></div>:null}
function Layout({admin=false}:{admin?:boolean}){return <div className={admin?'app-shell admin-layout':'app-shell owner-layout'}><Header admin={admin}/>{admin&&<div className="admin-shell"><AdminSidebar/><div className="admin-workspace"><AdminMobileMenu/><main className="main-content" id="main"><Outlet/></main><Footer/></div></div>}{!admin&&<><main className="main-content" id="main"><Outlet/></main><Footer/></>}<ResetListener/><Toast/></div>}
function Footer(){return <footer className="site-footer"><span>Portal del Edificio · Versión demo</span><span>Todos los datos son ficticios. <Link to="/servicios/chat">Contactar administración</Link></span></footer>}
function Toast(){const {toast}=usePortal();return toast?<div className="toast" role="status">{toast}</div>:null}
function AppRoutes(){return <Routes><Route element={<Layout/>}><Route index element={<HomePage/>}/><Route path="novedades" element={<NoticesPage/>}/><Route path="novedades/:id" element={<NoticeDetail/>}/><Route path="edificio" element={<BuildingPage/>}/><Route path="edificio/expensas" element={<ExpensesPage/>}/><Route path="edificio/reuniones" element={<MeetingsPage/>}/><Route path="edificio/encuestas" element={<PollsPage/>}/><Route path="edificio/documentos" element={<DocumentsPage/>}/><Route path="edificio/cuentas" element={<FinancesPage/>}/><Route path="edificio/obras" element={<WorksPage/>}/><Route path="servicios" element={<ServicesPage/>}/><Route path="servicios/sum" element={<SumPage/>}/><Route path="servicios/reclamos" element={<IssuesPage/>}/><Route path="servicios/chat" element={<ChatPage/>}/><Route path="servicios/contactos" element={<ContactsPage/>}/><Route path="servicios/urgencias" element={<UrgenciesPage/>}/><Route path="mas" element={<MorePage/>}/><Route path="mas/disponibilidades" element={<ListingsPage/>}/><Route path="mas/objetos" element={<LostPage/>}/><Route path="mas/preguntas" element={<FaqPage/>}/><Route path="mas/calendario" element={<CalendarPage/>}/><Route path="mas/estado" element={<StatePage/>}/></Route><Route path="admin" element={<Layout admin/>}><Route index element={<AdminHomePage/>}/><Route path="comunicaciones" element={<NoticesPage admin/>}/><Route path="finanzas" element={<FinancesPage admin/>}/><Route path="comunidad" element={<AdminCommunityPage/>}/><Route path="servicios" element={<AdminServicesPage/>}/><Route path="contenido" element={<AdminContentPage/>}/></Route><Route path="*" element={<Layout/>}/></Routes>}
export default function App(){return <BrowserRouter><PortalProvider><AppRoutes/></PortalProvider></BrowserRouter>}
