import { useEffect, useState } from 'react';
import { BrowserRouter, Link, NavLink, Outlet, Route, Routes, useLocation } from 'react-router-dom';
import { Building2, FileText, Home, LayoutDashboard, Menu, MessageCircle, MoreHorizontal, Newspaper, Sparkles, X } from 'lucide-react';
import { PortalProvider, usePortal } from './hooks/usePortal';
import { AdminHomePage } from './features/owner/AdminHome';
import { OwnerHomePage } from './features/owner/OwnerHome';
import { OwnerMenuPage } from './features/owner/OwnerMenu';
import { AdminMenuPage } from './features/owner/AdminMenu';
import { NoticesPage, NoticeDetail } from './features/notices/Notices';
import { AdminContentPage, BuildingPage, DocumentsPage, FaqPage, ListingsPage, LostPage, StatePage, WorksPage } from './features/content/Content';
import { FinancesPage, ExpensesPage } from './features/finances';
import { ServicesPage, ChatPage, ContactsPage, UrgenciesPage, AdminServicesPage, SumPage, IssuesPage } from './features/services';
import { MeetingsPage, PollsPage, CalendarPage, AdminCommunityPage } from './features/community';
import { DemoEntryPage, PublicBuildingPage, PublicContactPage, PublicHomePage, PublicLayout, PublicNewsPage } from './features/public/Public';
import './styles/global.css';

const ownerNav = [{ to: '/demo/propietario', label: 'Inicio', Icon: Home, end: true }, { to: '/demo/propietario/novedades', label: 'Novedades', Icon: Newspaper }, { to: '/demo/propietario/edificio', label: 'Mi edificio', Icon: Building2 }, { to: '/demo/propietario/mas', label: 'Menú', Icon: MoreHorizontal }];
const adminNav = [{ to: '/demo/administracion', label: 'Inicio', Icon: LayoutDashboard, end: true }, { to: '/demo/administracion/comunicaciones', label: 'Comunicaciones', Icon: MessageCircle }, { to: '/demo/administracion/finanzas', label: 'Finanzas', Icon: FileText }, { to: '/demo/administracion/menu', label: 'Menú', Icon: MoreHorizontal }];

function Header({ admin }: { admin: boolean }) { const location = useLocation(); const ownerPath = location.pathname.startsWith('/demo/') ? '/demo/propietario' : '/'; const adminPath = location.pathname.startsWith('/demo/') ? '/demo/administracion' : '/admin'; return <header className="site-header"><div className="header-inner"><Link to="/" className="brand"><span className="brand-mark"><Building2 size={25} /></span><span><strong>Edificio 13 y 34</strong><small>Portal de información · Demo</small></span></Link><div className="view-controls"><span className="demo-label">{admin ? 'Demo administración' : 'Demo propietario'}</span><div className="role-switch" aria-label="Cambiar demo"><Link className={!admin ? 'active' : ''} to={ownerPath}><Home size={16} />Propietario</Link><Link className={admin ? 'active' : ''} to={adminPath}><LayoutDashboard size={16} />Administración</Link></div></div></div>{!admin && <OwnerNav />}</header>; }
function OwnerNav() { return <nav className="owner-nav" aria-label="Navegación principal"><div className="owner-nav-inner">{ownerNav.map(({ to, label, Icon, end }) => <NavLink key={to} to={to} end={end}><Icon size={22} /><span>{label}</span></NavLink>)}</div></nav>; }
function AdminSidebar() { return <aside className="admin-sidebar"><p>Administración · Demo</p>{adminNav.map(({ to, label, Icon, end }) => <NavLink key={to} to={to} end={end}><Icon size={20} /><span>{label}</span></NavLink>)}<button className="button secondary reset-button" onClick={() => window.dispatchEvent(new CustomEvent('open-demo-reset'))}><Sparkles size={17} />Restablecer datos demo</button></aside>; }
function AdminMobileMenu() { const [open, setOpen] = useState(false); return <div className="admin-mobile-menu"><span>Administración · Demo</span><button className="button secondary small" aria-expanded={open} onClick={() => setOpen(v => !v)}>{open ? <X size={18} /> : <Menu size={18} />}Menú</button>{open && <div className="drawer-backdrop" onClick={() => setOpen(false)}><div className="drawer-nav" onClick={e => e.stopPropagation()}><div className="drawer-heading"><strong>Secciones</strong><button className="icon-button" aria-label="Cerrar menú" title="Cerrar menú" onClick={() => setOpen(false)}><X size={20} /></button></div>{adminNav.map(({ to, label, Icon, end }) => <NavLink key={to} to={to} end={end} onClick={() => setOpen(false)}><Icon size={20} />{label}</NavLink>)}<ResetDemoButton /></div></div>}</div>; }
function ResetDemoButton() { const { reset } = usePortal(); return <button className="button secondary" onClick={() => { if (window.confirm('¿Restablecer todos los datos demo? Se perderán los cambios locales.')) reset(); }}><Sparkles size={17} />Restablecer datos demo</button>; }
function ResetListener() { const { reset } = usePortal(); return <>{useResetEvent(reset)}</>; }
function useResetEvent(reset: () => void) { const [open, setOpen] = useState(false); useEffect(() => { const handler = () => setOpen(true); window.addEventListener('open-demo-reset', handler); return () => window.removeEventListener('open-demo-reset', handler); }, []); return open ? <div className="reset-popover"><p>¿Restablecer todos los datos demo? Se perderán los cambios locales.</p><div className="form-actions"><button className="button secondary" onClick={() => setOpen(false)}>Cancelar</button><button className="button" onClick={() => { reset(); setOpen(false); }}>Restablecer</button></div></div> : null; }
function Layout({ admin = false }: { admin?: boolean }) { return <div className={admin ? 'app-shell admin-layout' : 'app-shell owner-layout'}><Header admin={admin} />{admin && <div className="admin-shell"><AdminSidebar /><div className="admin-workspace"><AdminMobileMenu /><main className="main-content" id="main"><Outlet /></main><Footer /></div></div>}{!admin && <><main className="main-content" id="main"><Outlet /></main><Footer /></>}<ResetListener /><Toast /></div>; }
function Footer() { return <footer className="site-footer"><span>Edificio 13 y 34 · Versión demo</span><span>Todos los datos son ficticios. <Link to="/demo/propietario/servicios/chat">Contactar administración</Link></span></footer>; }
function Toast() { const { toast } = usePortal(); return toast ? <div className="toast" role="status">{toast}</div> : null; }

function OwnerRouteChildren() { return <><Route index element={<OwnerHomePage />} /><Route path="novedades" element={<NoticesPage />} /><Route path="novedades/:id" element={<NoticeDetail />} /><Route path="edificio" element={<BuildingPage />} /><Route path="edificio/expensas" element={<ExpensesPage />} /><Route path="edificio/reuniones" element={<MeetingsPage />} /><Route path="edificio/encuestas" element={<PollsPage />} /><Route path="edificio/documentos" element={<DocumentsPage />} /><Route path="edificio/cuentas" element={<FinancesPage />} /><Route path="edificio/obras" element={<WorksPage />} /><Route path="servicios" element={<ServicesPage />} /><Route path="servicios/sum" element={<SumPage />} /><Route path="servicios/reclamos" element={<IssuesPage />} /><Route path="servicios/chat" element={<ChatPage />} /><Route path="servicios/contactos" element={<ContactsPage />} /><Route path="servicios/urgencias" element={<UrgenciesPage />} /><Route path="mas" element={<OwnerMenuPage />} /><Route path="mas/disponibilidades" element={<ListingsPage />} /><Route path="mas/objetos" element={<LostPage />} /><Route path="mas/preguntas" element={<FaqPage />} /><Route path="mas/calendario" element={<CalendarPage />} /><Route path="mas/estado" element={<StatePage />} /></>; }
function AdminRouteChildren() { return <><Route index element={<AdminHomePage />} /><Route path="comunicaciones" element={<NoticesPage admin />} /><Route path="finanzas" element={<FinancesPage admin />} /><Route path="menu" element={<AdminMenuPage />} /><Route path="comunidad" element={<AdminCommunityPage />} /><Route path="servicios" element={<AdminServicesPage />} /><Route path="contenido" element={<AdminContentPage />} /></>; }
function AppRoutes() { return <Routes><Route index element={<PublicHomePage />} /><Route path="novedades" element={<PublicNewsPage />} /><Route path="novedades/:id" element={<PublicLayout><NoticeDetail /></PublicLayout>} /><Route path="edificio" element={<PublicBuildingPage />} /><Route path="contacto" element={<PublicContactPage />} /><Route path="demo" element={<DemoEntryPage />} /><Route path="demo/propietario" element={<Layout />}>{OwnerRouteChildren()}</Route><Route element={<Layout />}>{OwnerRouteChildren()}</Route><Route path="admin" element={<Layout admin />}>{AdminRouteChildren()}</Route><Route path="demo/administracion" element={<Layout admin />}>{AdminRouteChildren()}</Route><Route path="*" element={<PublicHomePage />} /></Routes>; }
export default function App() { return <BrowserRouter><PortalProvider><AppRoutes /></PortalProvider></BrowserRouter>; }
